version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 6606:3306
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

